"""empty message

Revision ID: 3474ac99db83
Revises: 84c9e94f83af
Create Date: 2022-04-01 14:42:25.106176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3474ac99db83'
down_revision = '84c9e94f83af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_admit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
