"""empty message

Revision ID: 84c9e94f83af
Revises: ad9d5801f593
Create Date: 2022-04-01 11:43:02.813754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c9e94f83af'
down_revision = 'ad9d5801f593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admit')
    # ### end Alembic commands ###
